/*
 * This JS METHOD is filtering the characters which are not required in some specific Field
 * It will allow the characters which are placed in a REGEX
 * Also Remove the highlighted CSS when user enter some text
 */
function filterValidations() {
    // JIRA ISSUE NO BAL-154
    //$('#B1').bind('keyup blur', function () {
    //    var node = $(this);
    //    node.val(node.val().replace(/[^A-Za-z0-9 ]/g, ''));
    //});
    //$('#B2').bind('keyup blur', function () {
    //    var node = $(this);
    //    node.val(node.val().replace(/[^0-9-]/g, ''));
    //});
    $('#B3').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^A-Za-z ]/g, ''));
    });
    $('#B5').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^0-9/]/g, ''));
    });
    $('#B6').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^0-9/]/g, ''));
    });
    $('#B7').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^0-9]/g, ''));
        var value = $(node).val();
        if (value.length <= 0) {
            $(node).addClass("highlight");
        }
        else {
            $(node).removeClass("highlight");
        }
    });
    $('#B7-A').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^0-9]/g, ''));
        var value = $(node).val();
        if (value.length <= 0) {
            $(node).addClass("highlight");
        }
        else {
            $(node).removeClass("highlight");
        }
    });
    $('#B7-B').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^0-9]/g, ''));
        var value = $(node).val();
        if (value.length <= 0) {
            $(node).addClass("highlight");
        }
        else {
            $(node).removeClass("highlight");
        }
    });
    $('#B7-C').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^0-9]/g, ''));
        var value = $(node).val();
        if (value.length <= 0) {
            $(node).addClass("highlight");
        }
        else {
            $(node).removeClass("highlight");
        }
    });
    $('#B7-D').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^0-9]/g, ''));
        var value = $(node).val();
        if (value.length <= 0) {
            $(node).addClass("highlight");
        }
        else {
            $(node).removeClass("highlight");
        }
    });
    $('#B7-E').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^0-9]/g, ''));
        var value = $(node).val();
        if (value.length <= 0) {
            $(node).addClass("highlight");
        }
        else {
            $(node).removeClass("highlight");
        }
    });
    $('#B7-F').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^0-9]/g, ''));
        var value = $(node).val();
        if (value.length <= 0) {
            $(node).addClass("highlight");
        }
        else {
            $(node).removeClass("highlight");
        }
    });
    $('#F1').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^0-9]/g, ''));
    });
    $('#F3').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^A-Za-z0-9 ]/g, ''));
    });
    $('#F4').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^A-Za-z0-9 ]/g, ''));
    });
    $('#F5').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^A-Za-z0-9 ]/g, ''));
    });
    $('#F6').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^A-Za-z ]/g, ''));
    });
    $('#F9').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^0-9]/g, ''));
    });
    $('#F10from').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^0-9]/g, ''));
    });
    $('#F10fromP').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^0-9]/g, ''));
    });
    $('#F10To').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^0-9]/g, ''));
    });
    $('#F10ToP').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^0-9]/g, ''));
    });
    $('#F11').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^0-9]/g, ''));
    });
    $('#F11P').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^0-9]/g, ''));
    });
    $('#F14c').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^A-Za-z0-9&() ]/g, ''));
    });
    $('#F14d').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^A-Za-z0-9&() ]/g, ''));
    });
    // restriction removed as per client requirements (JIRA-ISSUE-127)
    //$('#J1').bind('keyup blur', function () {
    //    var node = $(this);
    //    node.val(node.val().replace(/[^A-Za-z ]/g, ''));
    //});
    //$('#J2').bind('keyup blur', function () {
    //    var node = $(this);
    //    node.val(node.val().replace(/[^A-Za-z ]/g, ''));
    //});
    //$('#J3').bind('keyup blur', function () {
    //    var node = $(this);
    //    node.val(node.val().replace(/[^A-Za-z ]/g, ''));
    //});
    //$('#J4').bind('keyup blur', function () {
    //    var node = $(this);
    //    node.val(node.val().replace(/[^A-Za-z0-9 ]/g, ''));
    //});
    $('#K1').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^A-Za-z ]/g, ''));
    });
    $('#K2').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^A-Za-z ]/g, ''));
    });
    $('#K3').bind('keyup blur', function () {
        var node = $(this);
        node.val(node.val().replace(/[^A-Za-z ]/g, ''));
    });
    // JIRA ISSUE NO BAL-153
    //$('#K4').bind('keyup blur', function () {
    //    var node = $(this);
    //    node.val(node.val().replace(/[^A-Za-z0-9 ]/g, ''));
    //});
    
}



function getB3Value(value) {
    debugger;
    if (value == "11-1011.00") return "Chief Executives";
    if (value == "11-1021.00") return "General and Operations Managers";
    if (value == "11-1031.00") return "Legislators";
    if (value == "11-2011.00") return "Advertising and Promotions Managers";
    if (value == "11-2021.00") return "Marketing Managers";
    if (value == "11-2022.00") return "Sales Managers";
    if (value == "11-2032.00") return "Public Relations Managers";
    if (value == "11-2033.00") return "Fundraising Managers";
    if (value == "11-3012.00") return "Administrative Services Managers";
    if (value == "11-3013.00") return "Facilities Managers";
    if (value == "11-3021.00") return "Computer and Information Systems Managers";
    if (value == "11-3031.00") return "Financial Managers";
    if (value == "11-3051.00") return "Industrial Production Managers";
    if (value == "11-3061.00") return "Purchasing Managers";
    if (value == "11-3071.00") return "Transportation, Storage, and Distribution Managers";
    if (value == "11-3111.00") return "Compensation and Benefits Managers";
    if (value == "11-3121.00") return "Human Resources Managers";
    if (value == "11-3131.00") return "Training and Development Managers";
    if (value == "11-9013.00") return "Farmers, Ranchers, and Other Agricultural Managers";
    if (value == "11-9021.00") return "Construction Managers";
    if (value == "11-9031.00") return "Education and Childcare Administrators, Preschool and Daycare";
    if (value == "11-9032.00") return "Education Administrators, Kindergarten through Secondary";
    if (value == "11-9033.00") return "Education Administrators, Postsecondary";
    if (value == "11-9039.00") return "Education Administrators, All Other";
    if (value == "11-9041.00") return "Architectural and Engineering Managers";
    if (value == "11-9051.00") return "Food Service Managers";
    if (value == "11-9071.00") return "Gambling Managers";
    if (value == "11-9072.00") return "Entertainment and Recreation Managers, Except Gambling";
    if (value == "11-9081.00") return "Lodging Managers";
    if (value == "11-9111.00") return "Medical and Health Services Managers";
    if (value == "11-9121.00") return "Natural Sciences Managers";
    if (value == "11-9131.00") return "Postmasters and Mail Superintendents";
    if (value == "11-9141.00") return "Property, Real Estate, and Community Association Managers";
    if (value == "11-9151.00") return "Social and Community Service Managers";
    if (value == "11-9161.00") return "Emergency Management Directors";
    if (value == "11-9171.00") return "Funeral Home Managers";
    if (value == "11-9179.00") return "Personal Service Managers, All Other";
    if (value == "11-9199.00") return "Managers, All Other";
    if (value == "13-1011.00") return "Agents and Business Managers of Artists, Performers, and Athletes";
    if (value == "13-1021.00") return "Buyers and Purchasing Agents, Farm Products";
    if (value == "13-1022.00") return "Wholesale and Retail Buyers, Except Farm Products";
    if (value == "13-1023.00") return "Purchasing Agents, Except Wholesale, Retail, and Farm Products";
    if (value == "13-1031.00") return "Claims Adjusters, Examiners, and Investigators";
    if (value == "13-1032.00") return "Insurance Appraisers, Auto Damage";
    if (value == "13-1041.00") return "Compliance Officers";
    if (value == "13-1051.00") return "Cost Estimators";
    if (value == "13-1071.00") return "Human Resources Specialists";
    if (value == "13-1074.00") return "Farm Labor Contractors";
    if (value == "13-1075.00") return "Labor Relations Specialists";
    if (value == "13-1081.00") return "Logisticians";
    if (value == "13-1082.00") return "Project Management Specialists";
    if (value == "13-1111.00") return "Management Analysts";
    if (value == "13-1121.00") return "Meeting, Convention, and Event Planners";
    if (value == "13-1131.00") return "Fundraisers";
    if (value == "13-1141.00") return "Compensation, Benefits, and Job Analysis Specialists";
    if (value == "13-1151.00") return "Training and Development Specialists";
    if (value == "13-1161.00") return "Market Research Analysts and Marketing Specialists";
    if (value == "13-1199.00") return "Business Operations Specialists, All Other";
    if (value == "13-2011.00") return "Accountants and Auditors";
    if (value == "13-2022.00") return "Appraisers of Personal and Business Property";
    if (value == "13-2023.00") return "Appraisers and Assessors of Real Estate";
    if (value == "13-2031.00") return "Budget Analysts";
    if (value == "13-2041.00") return "Credit Analysts";
    if (value == "13-2051.00") return "Financial and Investment Analysts";
    if (value == "13-2052.00") return "Personal Financial Advisors";
    if (value == "13-2053.00") return "Insurance Underwriters";
    if (value == "13-2054.00") return "Financial Risk Specialists";
    if (value == "13-2061.00") return "Financial Examiners";
    if (value == "13-2071.00") return "Credit Counselors";
    if (value == "13-2072.00") return "Loan Officers";
    if (value == "13-2081.00") return "Tax Examiners and Collectors, and Revenue Agents";
    if (value == "13-2082.00") return "Tax Preparers";
    if (value == "13-2099.00") return "Financial Specialists, All Other";
    if (value == "15-1211.00") return "Computer Systems Analysts";
    if (value == "15-1212.00") return "Information Security Analysts";
    if (value == "15-1221.00") return "Computer and Information Research Scientists";
    if (value == "15-1231.00") return "Computer Network Support Specialists";
    if (value == "15-1232.00") return "Computer User Support Specialists";
    if (value == "15-1241.00") return "Computer Network Architects";
    if (value == "15-1242.00") return "Database Administrators";
    if (value == "15-1243.00") return "Database Architects";
    if (value == "15-1244.00") return "Network and Computer Systems Administrators";
    if (value == "15-1251.00") return "Computer Programmers";
    if (value == "15-1252.00") return "Software Developers";
    if (value == "15-1253.00") return "Software Quality Assurance Analysts and Testers";
    if (value == "15-1254.00") return "Web Developers";
    if (value == "15-1255.00") return "Web and Digital Interface Designers";
    if (value == "15-1299.00") return "Computer Occupations, All Other";
    if (value == "15-2011.00") return "Actuaries";
    if (value == "15-2021.00") return "Mathematicians";
    if (value == "15-2031.00") return "Operations Research Analysts";
    if (value == "15-2041.00") return "Statisticians";
    if (value == "15-2051.00") return "Data Scientists";
    if (value == "15-2099.00") return "Mathematical Science Occupations, All Other";
    if (value == "17-1011.00") return "Architects, Except Landscape and Naval";
    if (value == "17-1012.00") return "Landscape Architects";
    if (value == "17-1021.00") return "Cartographers and Photogrammetrists";
    if (value == "17-1022.00") return "Surveyors";
    if (value == "17-2011.00") return "Aerospace Engineers";
    if (value == "17-2021.00") return "Agricultural Engineers";
    if (value == "17-2031.00") return "Bioengineers and Biomedical Engineers";
    if (value == "17-2041.00") return "Chemical Engineers";
    if (value == "17-2051.00") return "Civil Engineers";
    if (value == "17-2061.00") return "Computer Hardware Engineers";
    if (value == "17-2071.00") return "Electrical Engineers";
    if (value == "17-2072.00") return "Electronics Engineers, Except Computer";
    if (value == "17-2081.00") return "Environmental Engineers";
    if (value == "17-2111.00") return "Health and Safety Engineers, Except Mining Safety Engineers and Inspectors";
    if (value == "17-2112.00") return "Industrial Engineers";
    if (value == "17-2121.00") return "Marine Engineers and Naval Architects";
    if (value == "17-2131.00") return "Materials Engineers";
    if (value == "17-2141.00") return "Mechanical Engineers";
    if (value == "17-2151.00") return "Mining and Geological Engineers, Including Mining Safety Engineers";
    if (value == "17-2161.00") return "Nuclear Engineers";
    if (value == "17-2171.00") return "Petroleum Engineers";
    if (value == "17-2199.00") return "Engineers, All Other";
    if (value == "17-3011.00") return "Architectural and Civil Drafters";
    if (value == "17-3012.00") return "Electrical and Electronics Drafters";
    if (value == "17-3013.00") return "Mechanical Drafters";
    if (value == "17-3019.00") return "Drafters, All Other";
    if (value == "17-3021.00") return "Aerospace Engineering and Operations Technologists and Technicians";
    if (value == "17-3022.00") return "Civil Engineering Technologists and Technicians";
    if (value == "17-3023.00") return "Electrical and Electronic Engineering Technologists and Technicians";
    if (value == "17-3024.00") return "Electro-Mechanical and Mechatronics Technologists and Technicians";
    if (value == "17-3025.00") return "Environmental Engineering Technologists and Technicians";
    if (value == "17-3026.00") return "Industrial Engineering Technologists and Technicians";
    if (value == "17-3027.00") return "Mechanical Engineering Technologists and Technicians";
    if (value == "17-3028.00") return "Calibration Technologists and Technicians";
    if (value == "17-3029.00") return "Engineering Technologists and Technicians, Except Drafters, All Other";
    if (value == "17-3031.00") return "Surveying and Mapping Technicians";
    if (value == "19-1011.00") return "Animal Scientists";
    if (value == "19-1012.00") return "Food Scientists and Technologists";
    if (value == "19-1013.00") return "Soil and Plant Scientists";
    if (value == "19-1021.00") return "Biochemists and Biophysicists";
    if (value == "19-1022.00") return "Microbiologists";
    if (value == "19-1023.00") return "Zoologists and Wildlife Biologists";
    if (value == "19-1029.00") return "Biological Scientists, All Other";
    if (value == "19-1031.00") return "Conservation Scientists";
    if (value == "19-1032.00") return "Foresters";
    if (value == "19-1041.00") return "Epidemiologists";
    if (value == "19-1042.00") return "Medical Scientists, Except Epidemiologists";
    if (value == "19-1099.00") return "Life Scientists, All Other";
    if (value == "19-2011.00") return "Astronomers";
    if (value == "19-2012.00") return "Physicists";
    if (value == "19-2021.00") return "Atmospheric and Space Scientists";
    if (value == "19-2031.00") return "Chemists";
    if (value == "19-2032.00") return "Materials Scientists";
    if (value == "19-2041.00") return "Environmental Scientists and Specialists, Including Health";
    if (value == "19-2042.00") return "Geoscientists, Except Hydrologists and Geographers";
    if (value == "19-2043.00") return "Hydrologists";
    if (value == "19-2099.00") return "Physical Scientists, All Other";
    if (value == "19-3011.00") return "Economists";
    if (value == "19-3022.00") return "Survey Researchers";
    if (value == "19-3032.00") return "Industrial-Organizational Psychologists";
    if (value == "19-3033.00") return "Clinical and Counseling Psychologists";
    if (value == "19-3034.00") return "School Psychologists";
    if (value == "19-3039.00") return "Psychologists, All Other";
    if (value == "19-3041.00") return "Sociologists";
    if (value == "19-3051.00") return "Urban and Regional Planners";
    if (value == "19-3091.00") return "Anthropologists and Archeologists";
    if (value == "19-3092.00") return "Geographers";
    if (value == "19-3093.00") return "Historians";
    if (value == "19-3094.00") return "Political Scientists";
    if (value == "19-3099.00") return "Social Scientists and Related Workers, All Other";
    if (value == "19-4012.00") return "Agricultural Technicians";
    if (value == "19-4013.00") return "Food Science Technicians";
    if (value == "19-4021.00") return "Biological Technicians";
    if (value == "19-4031.00") return "Chemical Technicians";
    if (value == "19-4042.00") return "Environmental Science and Protection Technicians, Including Health";
    if (value == "19-4043.00") return "Geological Technicians, Except Hydrologic Technicians";
    if (value == "19-4044.00") return "Hydrologic Technicians";
    if (value == "19-4051.00") return "Nuclear Technicians";
    if (value == "19-4061.00") return "Social Science Research Assistants";
    if (value == "19-4071.00") return "Forest and Conservation Technicians";
    if (value == "19-4092.00") return "Forensic Science Technicians";
    if (value == "19-4099.00") return "Life, Physical, and Social Science Technicians, All Other";
    if (value == "19-5011.00") return "Occupational Health and Safety Specialists";
    if (value == "19-5012.00") return "Occupational Health and Safety Technicians";
    if (value == "21-1011.00") return "Substance Abuse and Behavioral Disorder Counselors";
    if (value == "21-1012.00") return "Educational, Guidance, and Career Counselors and Advisors";
    if (value == "21-1013.00") return "Marriage and Family Therapists";
    if (value == "21-1014.00") return "Mental Health Counselors";
    if (value == "21-1015.00") return "Rehabilitation Counselors";
    if (value == "21-1019.00") return "Counselors, All Other";
    if (value == "21-1021.00") return "Child, Family, and School Social Workers";
    if (value == "21-1022.00") return "Healthcare Social Workers";
    if (value == "21-1023.00") return "Mental Health and Substance Abuse Social Workers";
    if (value == "21-1029.00") return "Social Workers, All Other";
    if (value == "21-1091.00") return "Health Education Specialists";
    if (value == "21-1092.00") return "Probation Officers and Correctional Treatment Specialists";
    if (value == "21-1093.00") return "Social and Human Service Assistants";
    if (value == "21-1094.00") return "Community Health Workers";
    if (value == "21-1099.00") return "Community and Social Service Specialists, All Other";
    if (value == "21-2011.00") return "Clergy";
    if (value == "21-2021.00") return "Directors, Religious Activities and Education";
    if (value == "21-2099.00") return "Religious Workers, All Other";
    if (value == "23-1011.00") return "Lawyers";
    if (value == "23-1012.00") return "Judicial Law Clerks";
    if (value == "23-1021.00") return "Administrative Law Judges, Adjudicators, and Hearing Officers";
    if (value == "23-1022.00") return "Arbitrators, Mediators, and Conciliators";
    if (value == "23-1023.00") return "Judges, Magistrate Judges, and Magistrates";
    if (value == "23-2011.00") return "Paralegals and Legal Assistants";
    if (value == "23-2093.00") return "Title Examiners, Abstractors, and Searchers";
    if (value == "23-2099.00") return "Legal Support Workers, All Other";
    if (value == "25-1011.00") return "Business Teachers, Postsecondary";
    if (value == "25-1021.00") return "Computer Science Teachers, Postsecondary";
    if (value == "25-1022.00") return "Mathematical Science Teachers, Postsecondary";
    if (value == "25-1031.00") return "Architecture Teachers, Postsecondary";
    if (value == "25-1032.00") return "Engineering Teachers, Postsecondary";
    if (value == "25-1041.00") return "Agricultural Sciences Teachers, Postsecondary";
    if (value == "25-1042.00") return "Biological Science Teachers, Postsecondary";
    if (value == "25-1043.00") return "Forestry and Conservation Science Teachers, Postsecondary";
    if (value == "25-1051.00") return "Atmospheric, Earth, Marine, and Space Sciences Teachers, Postsecondary";
    if (value == "25-1052.00") return "Chemistry Teachers, Postsecondary";
    if (value == "25-1053.00") return "Environmental Science Teachers, Postsecondary";
    if (value == "25-1054.00") return "Physics Teachers, Postsecondary";
    if (value == "25-1061.00") return "Anthropology and Archeology Teachers, Postsecondary";
    if (value == "25-1062.00") return "Area, Ethnic, and Cultural Studies Teachers, Postsecondary";
    if (value == "25-1063.00") return "Economics Teachers, Postsecondary";
    if (value == "25-1064.00") return "Geography Teachers, Postsecondary";
    if (value == "25-1065.00") return "Political Science Teachers, Postsecondary";
    if (value == "25-1066.00") return "Psychology Teachers, Postsecondary";
    if (value == "25-1067.00") return "Sociology Teachers, Postsecondary";
    if (value == "25-1069.00") return "Social Sciences Teachers, Postsecondary, All Other";
    if (value == "25-1071.00") return "Health Specialties Teachers, Postsecondary";
    if (value == "25-1072.00") return "Nursing Instructors and Teachers, Postsecondary";
    if (value == "25-1081.00") return "Education Teachers, Postsecondary";
    if (value == "25-1082.00") return "Library Science Teachers, Postsecondary";
    if (value == "25-1111.00") return "Criminal Justice and Law Enforcement Teachers, Postsecondary";
    if (value == "25-1112.00") return "Law Teachers, Postsecondary";
    if (value == "25-1113.00") return "Social Work Teachers, Postsecondary";
    if (value == "25-1121.00") return "Art, Drama, and Music Teachers, Postsecondary";
    if (value == "25-1122.00") return "Communications Teachers, Postsecondary";
    if (value == "25-1123.00") return "English Language and Literature Teachers, Postsecondary";
    if (value == "25-1124.00") return "Foreign Language and Literature Teachers, Postsecondary";
    if (value == "25-1125.00") return "History Teachers, Postsecondary";
    if (value == "25-1126.00") return "Philosophy and Religion Teachers, Postsecondary";
    if (value == "25-1192.00") return "Family and Consumer Sciences Teachers, Postsecondary";
    if (value == "25-1193.00") return "Recreation and Fitness Studies Teachers, Postsecondary";
    if (value == "25-1194.00") return "Career/Technical Education Teachers, Postsecondary";
    if (value == "25-1199.00") return "Postsecondary Teachers, All Other";
    if (value == "25-2011.00") return "Preschool Teachers, Except Special Education";
    if (value == "25-2012.00") return "Kindergarten Teachers, Except Special Education";
    if (value == "25-2021.00") return "Elementary School Teachers, Except Special Education";
    if (value == "25-2022.00") return "Middle School Teachers, Except Special and Career/Technical Education";
    if (value == "25-2023.00") return "Career/Technical Education Teachers, Middle School";
    if (value == "25-2031.00") return "Secondary School Teachers, Except Special and Career/Technical Education";
    if (value == "25-2032.00") return "Career/Technical Education Teachers, Secondary School";
    if (value == "25-2051.00") return "Special Education Teachers, Preschool";
    if (value == "25-2055.00") return "Special Education Teachers, Kindergarten";
    if (value == "25-2056.00") return "Special Education Teachers, Elementary School";
    if (value == "25-2057.00") return "Special Education Teachers, Middle School";
    if (value == "25-2058.00") return "Special Education Teachers, Secondary School";
    if (value == "25-2059.00") return "Special Education Teachers, All Other";
    if (value == "25-3011.00") return "Adult Basic Education, Adult Secondary Education, and English as a Second Language Instructors";
    if (value == "25-3021.00") return "Self-Enrichment Teachers";
    if (value == "25-3031.00") return "Substitute Teachers, Short-Term";
    if (value == "25-3041.00") return "Tutors";
    if (value == "25-3099.00") return "Teachers and Instructors, All Other";
    if (value == "25-4011.00") return "Archivists";
    if (value == "25-4012.00") return "Curators";
    if (value == "25-4013.00") return "Museum Technicians and Conservators";
    if (value == "25-4022.00") return "Librarians and Media Collections Specialists";
    if (value == "25-4031.00") return "Library Technicians";
    if (value == "25-9021.00") return "Farm and Home Management Educators";
    if (value == "25-9031.00") return "Instructional Coordinators";
    if (value == "25-9042.00") return "Teaching Assistants, Preschool, Elementary, Middle, and Secondary School, Except Special Education";
    if (value == "25-9043.00") return "Teaching Assistants, Special Education";
    if (value == "25-9044.00") return "Teaching Assistants, Postsecondary";
    if (value == "25-9049.00") return "Teaching Assistants, All Other";
    if (value == "25-9099.00") return "Educational Instruction and Library Workers, All Other";
    if (value == "27-1011.00") return "Art Directors";
    if (value == "27-1012.00") return "Craft Artists";
    if (value == "27-1013.00") return "Fine Artists, Including Painters, Sculptors, and Illustrators";
    if (value == "27-1014.00") return "Special Effects Artists and Animators";
    if (value == "27-1019.00") return "Artists and Related Workers, All Other";
    if (value == "27-1021.00") return "Commercial and Industrial Designers";
    if (value == "27-1022.00") return "Fashion Designers";
    if (value == "27-1023.00") return "Floral Designers";
    if (value == "27-1024.00") return "Graphic Designers";
    if (value == "27-1025.00") return "Interior Designers";
    if (value == "27-1026.00") return "Merchandise Displayers and Window Trimmers";
    if (value == "27-1027.00") return "Set and Exhibit Designers";
    if (value == "27-1029.00") return "Designers, All Other";
    if (value == "27-2011.00") return "Actors";
    if (value == "27-2012.00") return "Producers and Directors";
    if (value == "27-2021.00") return "Athletes and Sports Competitors";
    if (value == "27-2022.00") return "Coaches and Scouts";
    if (value == "27-2023.00") return "Umpires, Referees, and Other Sports Officials";
    if (value == "27-2031.00") return "Dancers";
    if (value == "27-2032.00") return "Choreographers";
    if (value == "27-2041.00") return "Music Directors and Composers";
    if (value == "27-2042.00") return "Musicians and Singers";
    if (value == "27-2091.00") return "Disc Jockeys, Except Radio";
    if (value == "27-2099.00") return "Entertainers and Performers, Sports and Related Workers, All Other";
    if (value == "27-3011.00") return "Broadcast Announcers and Radio Disc Jockeys";
    if (value == "27-3023.00") return "News Analysts, Reporters, and Journalists";
    if (value == "27-3031.00") return "Public Relations Specialists";
    if (value == "27-3041.00") return "Editors";
    if (value == "27-3042.00") return "Technical Writers";
    if (value == "27-3043.00") return "Writers and Authors";
    if (value == "27-3091.00") return "Interpreters and Translators";
    if (value == "27-3092.00") return "Court Reporters and Simultaneous Captioners";
    if (value == "27-3099.00") return "Media and Communication Workers, All Other";
    if (value == "27-4011.00") return "Audio and Video Technicians";
    if (value == "27-4012.00") return "Broadcast Technicians";
    if (value == "27-4014.00") return "Sound Engineering Technicians";
    if (value == "27-4015.00") return "Lighting Technicians";
    if (value == "27-4021.00") return "Photographers";
    if (value == "27-4031.00") return "Camera Operators, Television, Video, and Film";
    if (value == "27-4032.00") return "Film and Video Editors";
    if (value == "27-4099.00") return "Media and Communication Equipment Workers, All Other";
    if (value == "29-1011.00") return "Chiropractors";
    if (value == "29-1021.00") return "Dentists, General";
    if (value == "29-1022.00") return "Oral and Maxillofacial Surgeons";
    if (value == "29-1023.00") return "Orthodontists";
    if (value == "29-1024.00") return "Prosthodontists";
    if (value == "29-1029.00") return "Dentists, All Other Specialists";
    if (value == "29-1031.00") return "Dietitians and Nutritionists";
    if (value == "29-1041.00") return "Optometrists";
    if (value == "29-1051.00") return "Pharmacists";
    if (value == "29-1071.00") return "Physician Assistants";
    if (value == "29-1081.00") return "Podiatrists";
    if (value == "29-1122.00") return "Occupational Therapists";
    if (value == "29-1123.00") return "Physical Therapists";
    if (value == "29-1124.00") return "Radiation Therapists";
    if (value == "29-1125.00") return "Recreational Therapists";
    if (value == "29-1126.00") return "Respiratory Therapists";
    if (value == "29-1127.00") return "Speech-Language Pathologists";
    if (value == "29-1128.00") return "Exercise Physiologists";
    if (value == "29-1129.00") return "Therapists, All Other";
    if (value == "29-1131.00") return "Veterinarians";
    if (value == "29-1141.00") return "Registered Nurses";
    if (value == "29-1151.00") return "Nurse Anesthetists";
    if (value == "29-1161.00") return "Nurse Midwives";
    if (value == "29-1171.00") return "Nurse Practitioners";
    if (value == "29-1181.00") return "Audiologists";
    if (value == "29-1211.00") return "Anesthesiologists";
    if (value == "29-1212.00") return "Cardiologists";
    if (value == "29-1213.00") return "Dermatologists";
    if (value == "29-1214.00") return "Emergency Medicine Physicians";
    if (value == "29-1215.00") return "Family Medicine Physicians";
    if (value == "29-1216.00") return "General Internal Medicine Physicians";
    if (value == "29-1217.00") return "Neurologists";
    if (value == "29-1218.00") return "Obstetricians and Gynecologists";
    if (value == "29-1221.00") return "Pediatricians, General";
    if (value == "29-1222.00") return "Physicians, Pathologists";
    if (value == "29-1223.00") return "Psychiatrists";
    if (value == "29-1224.00") return "Radiologists";
    if (value == "29-1229.00") return "Physicians, All Other";
    if (value == "29-1241.00") return "Ophthalmologists, Except Pediatric";
    if (value == "29-1242.00") return "Orthopedic Surgeons, Except Pediatric";
    if (value == "29-1243.00") return "Pediatric Surgeons";
    if (value == "29-1249.00") return "Surgeons, All Other";
    if (value == "29-1291.00") return "Acupuncturists";
    if (value == "29-1292.00") return "Dental Hygienists";
    if (value == "29-1299.00") return "Healthcare Diagnosing or Treating Practitioners, All Other";
    if (value == "29-2011.00") return "Medical and Clinical Laboratory Technologists";
    if (value == "29-2012.00") return "Medical and Clinical Laboratory Technicians";
    if (value == "29-2031.00") return "Cardiovascular Technologists and Technicians";
    if (value == "29-2032.00") return "Diagnostic Medical Sonographers";
    if (value == "29-2033.00") return "Nuclear Medicine Technologists";
    if (value == "29-2034.00") return "Radiologic Technologists and Technicians";
    if (value == "29-2035.00") return "Magnetic Resonance Imaging Technologists";
    if (value == "29-2036.00") return "Medical Dosimetrists";
    if (value == "29-2042.00") return "Emergency Medical Technicians";
    if (value == "29-2043.00") return "Paramedics";
    if (value == "29-2051.00") return "Dietetic Technicians";
    if (value == "29-2052.00") return "Pharmacy Technicians";
    if (value == "29-2053.00") return "Psychiatric Technicians";
    if (value == "29-2055.00") return "Surgical Technologists";
    if (value == "29-2056.00") return "Veterinary Technologists and Technicians";
    if (value == "29-2057.00") return "Ophthalmic Medical Technicians";
    if (value == "29-2061.00") return "Licensed Practical and Licensed Vocational Nurses";
    if (value == "29-2072.00") return "Medical Records Specialists";
    if (value == "29-2081.00") return "Opticians, Dispensing";
    if (value == "29-2091.00") return "Orthotists and Prosthetists";
    if (value == "29-2092.00") return "Hearing Aid Specialists";
    if (value == "29-2099.00") return "Health Technologists and Technicians, All Other";
    if (value == "29-9021.00") return "Health Information Technologists and Medical Registrars";
    if (value == "29-9091.00") return "Athletic Trainers";
    if (value == "29-9092.00") return "Genetic Counselors";
    if (value == "29-9093.00") return "Surgical Assistants";
    if (value == "29-9099.00") return "Healthcare Practitioners and Technical Workers, All Other";
    if (value == "31-1121.00") return "Home Health Aides";
    if (value == "31-1122.00") return "Personal Care Aides";
    if (value == "31-1131.00") return "Nursing Assistants";
    if (value == "31-1132.00") return "Orderlies";
    if (value == "31-1133.00") return "Psychiatric Aides";
    if (value == "31-2011.00") return "Occupational Therapy Assistants";
    if (value == "31-2012.00") return "Occupational Therapy Aides";
    if (value == "31-2021.00") return "Physical Therapist Assistants";
    if (value == "31-2022.00") return "Physical Therapist Aides";
    if (value == "31-9011.00") return "Massage Therapists";
    if (value == "31-9091.00") return "Dental Assistants";
    if (value == "31-9092.00") return "Medical Assistants";
    if (value == "31-9093.00") return "Medical Equipment Preparers";
    if (value == "31-9094.00") return "Medical Transcriptionists";
    if (value == "31-9095.00") return "Pharmacy Aides";
    if (value == "31-9096.00") return "Veterinary Assistants and Laboratory Animal Caretakers";
    if (value == "31-9097.00") return "Phlebotomists";
    if (value == "31-9099.00") return "Healthcare Support Workers, All Other";
    if (value == "33-1011.00") return "First-Line Supervisors of Correctional Officers";
    if (value == "33-1012.00") return "First-Line Supervisors of Police and Detectives";
    if (value == "33-1021.00") return "First-Line Supervisors of Fire Fighting and Prevention Workers";
    if (value == "33-1091.00") return "First-Line Supervisors of Security Workers";
    if (value == "33-1099.00") return "First-Line Supervisors of Protective Service Workers, All Other";
    if (value == "33-2011.00") return "Firefighters";
    if (value == "33-2021.00") return "Fire Inspectors and Investigators";
    if (value == "33-2022.00") return "Forest Fire Inspectors and Prevention Specialists";
    if (value == "33-3011.00") return "Bailiffs";
    if (value == "33-3012.00") return "Correctional Officers and Jailers";
    if (value == "33-3021.00") return "Detectives and Criminal Investigators";
    if (value == "33-3031.00") return "Fish and Game Wardens";
    if (value == "33-3041.00") return "Parking Enforcement Workers";
    if (value == "33-3051.00") return "Police and Sheriff's Patrol Officers";
    if (value == "33-3052.00") return "Transit and Railroad Police";
    if (value == "33-9011.00") return "Animal Control Workers";
    if (value == "33-9021.00") return "Private Detectives and Investigators";
    if (value == "33-9031.00") return "Gambling Surveillance Officers and Gambling Investigators";
    if (value == "33-9032.00") return "Security Guards";
    if (value == "33-9091.00") return "Crossing Guards and Flaggers";
    if (value == "33-9092.00") return "Lifeguards, Ski Patrol, and Other Recreational Protective Service Workers";
    if (value == "33-9093.00") return "Transportation Security Screeners";
    if (value == "33-9094.00") return "School Bus Monitors";
    if (value == "33-9099.00") return "Protective Service Workers, All Other";
    if (value == "35-1011.00") return "Chefs and Head Cooks";
    if (value == "35-1012.00") return "First-Line Supervisors of Food Preparation and Serving Workers";
    if (value == "35-2011.00") return "Cooks, Fast Food";
    if (value == "35-2012.00") return "Cooks, Institution and Cafeteria";
    if (value == "35-2013.00") return "Cooks, Private Household";
    if (value == "35-2014.00") return "Cooks, Restaurant";
    if (value == "35-2015.00") return "Cooks, Short Order";
    if (value == "35-2019.00") return "Cooks, All Other";
    if (value == "35-2021.00") return "Food Preparation Workers";
    if (value == "35-3011.00") return "Bartenders";
    if (value == "35-3023.00") return "Fast Food and Counter Workers";
    if (value == "35-3031.00") return "Waiters and Waitresses";
    if (value == "35-3041.00") return "Food Servers, Nonrestaurant";
    if (value == "35-9011.00") return "Dining Room and Cafeteria Attendants and Bartender Helpers";
    if (value == "35-9021.00") return "Dishwashers";
    if (value == "35-9031.00") return "Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop";
    if (value == "35-9099.00") return "Food Preparation and Serving Related Workers, All Other";
    if (value == "37-1011.00") return "First-Line Supervisors of Housekeeping and Janitorial Workers";
    if (value == "37-1012.00") return "First-Line Supervisors of Landscaping, Lawn Service, and Groundskeeping Workers";
    if (value == "37-2011.00") return "Janitors and Cleaners, Except Maids and Housekeeping Cleaners";
    if (value == "37-2012.00") return "Maids and Housekeeping Cleaners";
    if (value == "37-2019.00") return "Building Cleaning Workers, All Other";
    if (value == "37-2021.00") return "Pest Control Workers";
    if (value == "37-3011.00") return "Landscaping and Groundskeeping Workers";
    if (value == "37-3012.00") return "Pesticide Handlers, Sprayers, and Applicators, Vegetation";
    if (value == "37-3013.00") return "Tree Trimmers and Pruners";
    if (value == "37-3019.00") return "Grounds Maintenance Workers, All Other";
    if (value == "39-1013.00") return "First-line Supervisors of Gambling Services Workers";
    if (value == "39-1014.00") return "First-line Supervisors of Entertainment and Recreation Workers, Except Gambling Services";
    if (value == "39-1022.00") return "First-Line Supervisors of Personal Service Workers";
    if (value == "39-2011.00") return "Animal Trainers";
    if (value == "39-2021.00") return "Animal Caretakers";
    if (value == "39-3011.00") return "Gambling Dealers";
    if (value == "39-3012.00") return "Gambling and Sports Book Writers and Runners";
    if (value == "39-3019.00") return "Gambling Service Workers, All Other";
    if (value == "39-3021.00") return "Motion Picture Projectionists";
    if (value == "39-3031.00") return "Ushers, Lobby Attendants, and Ticket Takers";
    if (value == "39-3091.00") return "Amusement and Recreation Attendants";
    if (value == "39-3092.00") return "Costume Attendants";
    if (value == "39-3093.00") return "Locker Room, Coatroom, and Dressing Room Attendants";
    if (value == "39-3099.00") return "Entertainment Attendants and Related Workers, All Other";
    if (value == "39-4011.00") return "Embalmers";
    if (value == "39-4012.00") return "Crematory Operators";
    if (value == "39-4021.00") return "Funeral Attendants";
    if (value == "39-4031.00") return "Morticians, Undertakers, and Funeral Arrangers";
    if (value == "39-5011.00") return "Barbers";
    if (value == "39-5012.00") return "Hairdressers, Hairstylists, and Cosmetologists";
    if (value == "39-5091.00") return "Makeup Artists, Theatrical and Performance";
    if (value == "39-5092.00") return "Manicurists and Pedicurists";
    if (value == "39-5093.00") return "Shampooers";
    if (value == "39-5094.00") return "Skincare Specialists";
    if (value == "39-6011.00") return "Baggage Porters and Bellhops";
    if (value == "39-6012.00") return "Concierges";
    if (value == "39-7011.00") return "Tour Guides and Escorts";
    if (value == "39-7012.00") return "Travel Guides";
    if (value == "39-9011.00") return "Childcare Workers";
    if (value == "39-9031.00") return "Exercise Trainers and Group Fitness Instructors";
    if (value == "39-9032.00") return "Recreation Workers";
    if (value == "39-9041.00") return "Residential Advisors";
    if (value == "39-9099.00") return "Personal Care and Service Workers, All Other";
    if (value == "41-1011.00") return "First-Line Supervisors of Retail Sales Workers";
    if (value == "41-1012.00") return "First-Line Supervisors of Non-Retail Sales Workers";
    if (value == "41-2011.00") return "Cashiers";
    if (value == "41-2012.00") return "Gambling Change Persons and Booth Cashiers";
    if (value == "41-2021.00") return "Counter and Rental Clerks";
    if (value == "41-2022.00") return "Parts Salespersons";
    if (value == "41-2031.00") return "Retail Salespersons";
    if (value == "41-3011.00") return "Advertising Sales Agents";
    if (value == "41-3021.00") return "Insurance Sales Agents";
    if (value == "41-3031.00") return "Securities, Commodities, and Financial Services Sales Agents";
    if (value == "41-3041.00") return "Travel Agents";
    if (value == "41-3091.00") return "Sales Representatives of Services, Except Advertising, Insurance, Financial Services, and Travel";
    if (value == "41-4011.00") return "Sales Representatives, Wholesale and Manufacturing, Technical and Scientific Products";
    if (value == "41-4012.00") return "Sales Representatives, Wholesale and Manufacturing, Except Technical and Scientific Products";
    if (value == "41-9011.00") return "Demonstrators and Product Promoters";
    if (value == "41-9012.00") return "Models";
    if (value == "41-9021.00") return "Real Estate Brokers";
    if (value == "41-9022.00") return "Real Estate Sales Agents";
    if (value == "41-9031.00") return "Sales Engineers";
    if (value == "41-9041.00") return "Telemarketers";
    if (value == "41-9091.00") return "Door-to-Door Sales Workers, News and Street Vendors, and Related Workers";
    if (value == "41-9099.00") return "Sales and Related Workers, All Other";
    if (value == "43-1011.00") return "First-Line Supervisors of Office and Administrative Support Workers";
    if (value == "43-2011.00") return "Switchboard Operators, Including Answering Service";
    if (value == "43-2021.00") return "Telephone Operators";
    if (value == "43-2099.00") return "Communications Equipment Operators, All Other";
    if (value == "43-3011.00") return "Bill and Account Collectors";
    if (value == "43-3021.00") return "Billing and Posting Clerks";
    if (value == "43-3031.00") return "Bookkeeping, Accounting, and Auditing Clerks";
    if (value == "43-3041.00") return "Gambling Cage Workers";
    if (value == "43-3051.00") return "Payroll and Timekeeping Clerks";
    if (value == "43-3061.00") return "Procurement Clerks";
    if (value == "43-3071.00") return "Tellers";
    if (value == "43-3099.00") return "Financial Clerks, All Other";
    if (value == "43-4011.00") return "Brokerage Clerks";
    if (value == "43-4021.00") return "Correspondence Clerks";
    if (value == "43-4031.00") return "Court, Municipal, and License Clerks";
    if (value == "43-4041.00") return "Credit Authorizers, Checkers, and Clerks";
    if (value == "43-4051.00") return "Customer Service Representatives";
    if (value == "43-4061.00") return "Eligibility Interviewers, Government Programs";
    if (value == "43-4071.00") return "File Clerks";
    if (value == "43-4081.00") return "Hotel, Motel, and Resort Desk Clerks";
    if (value == "43-4111.00") return "Interviewers, Except Eligibility and Loan";
    if (value == "43-4121.00") return "Library Assistants, Clerical";
    if (value == "43-4131.00") return "Loan Interviewers and Clerks";
    if (value == "43-4141.00") return "New Accounts Clerks";
    if (value == "43-4151.00") return "Order Clerks";
    if (value == "43-4161.00") return "Human Resources Assistants, Except Payroll and Timekeeping";
    if (value == "43-4171.00") return "Receptionists and Information Clerks";
    if (value == "43-4181.00") return "Reservation and Transportation Ticket Agents and Travel Clerks";
    if (value == "43-4199.00") return "Information and Record Clerks, All Other";
    if (value == "43-5011.00") return "Cargo and Freight Agents";
    if (value == "43-5021.00") return "Couriers and Messengers";
    if (value == "43-5031.00") return "Public Safety Telecommunicators";
    if (value == "43-5032.00") return "Dispatchers, Except Police, Fire, and Ambulance";
    if (value == "43-5041.00") return "Meter Readers, Utilities";
    if (value == "43-5051.00") return "Postal Service Clerks";
    if (value == "43-5052.00") return "Postal Service Mail Carriers";
    if (value == "43-5053.00") return "Postal Service Mail Sorters, Processors, and Processing Machine Operators";
    if (value == "43-5061.00") return "Production, Planning, and Expediting Clerks";
    if (value == "43-5071.00") return "Shipping, Receiving, and Inventory Clerks";
    if (value == "43-5111.00") return "Weighers, Measurers, Checkers, and Samplers, Recordkeeping";
    if (value == "43-6011.00") return "Executive Secretaries and Executive Administrative Assistants";
    if (value == "43-6012.00") return "Legal Secretaries and Administrative Assistants";
    if (value == "43-6013.00") return "Medical Secretaries and Administrative Assistants";
    if (value == "43-6014.00") return "Secretaries and Administrative Assistants, Except Legal, Medical, and Executive";
    if (value == "43-9021.00") return "Data Entry Keyers";
    if (value == "43-9022.00") return "Word Processors and Typists";
    if (value == "43-9031.00") return "Desktop Publishers";
    if (value == "43-9041.00") return "Insurance Claims and Policy Processing Clerks";
    if (value == "43-9051.00") return "Mail Clerks and Mail Machine Operators, Except Postal Service";
    if (value == "43-9061.00") return "Office Clerks, General";
    if (value == "43-9071.00") return "Office Machine Operators, Except Computer";
    if (value == "43-9081.00") return "Proofreaders and Copy Markers";
    if (value == "43-9111.00") return "Statistical Assistants";
    if (value == "43-9199.00") return "Office and Administrative Support Workers, All Other";
    if (value == "45-1011.00") return "First-Line Supervisors of Farming, Fishing, and Forestry Workers";
    if (value == "45-2011.00") return "Agricultural Inspectors";
    if (value == "45-2021.00") return "Animal Breeders";
    if (value == "45-2041.00") return "Graders and Sorters, Agricultural Products";
    if (value == "45-2091.00") return "Agricultural Equipment Operators";
    if (value == "45-2092.00") return "Farmworkers and Laborers, Crop, Nursery, and Greenhouse";
    if (value == "45-2093.00") return "Farmworkers, Farm, Ranch, and Aquacultural Animals";
    if (value == "45-2099.00") return "Agricultural Workers, All Other";
    if (value == "45-3031.00") return "Fishing and Hunting Workers";
    if (value == "45-4011.00") return "Forest and Conservation Workers";
    if (value == "45-4021.00") return "Fallers";
    if (value == "45-4022.00") return "Logging Equipment Operators";
    if (value == "45-4023.00") return "Log Graders and Scalers";
    if (value == "45-4029.00") return "Logging Workers, All Other";
    if (value == "47-1011.00") return "First-Line Supervisors of Construction Trades and Extraction Workers";
    if (value == "47-2011.00") return "Boilermakers";
    if (value == "47-2021.00") return "Brickmasons and Blockmasons";
    if (value == "47-2022.00") return "Stonemasons";
    if (value == "47-2031.00") return "Carpenters";
    if (value == "47-2041.00") return "Carpet Installers";
    if (value == "47-2042.00") return "Floor Layers, Except Carpet, Wood, and Hard Tiles";
    if (value == "47-2043.00") return "Floor Sanders and Finishers";
    if (value == "47-2044.00") return "Tile and Stone Setters";
    if (value == "47-2051.00") return "Cement Masons and Concrete Finishers";
    if (value == "47-2053.00") return "Terrazzo Workers and Finishers";
    if (value == "47-2061.00") return "Construction Laborers";
    if (value == "47-2071.00") return "Paving, Surfacing, and Tamping Equipment Operators";
    if (value == "47-2072.00") return "Pile Driver Operators";
    if (value == "47-2073.00") return "Operating Engineers and Other Construction Equipment Operators";
    if (value == "47-2081.00") return "Drywall and Ceiling Tile Installers";
    if (value == "47-2082.00") return "Tapers";
    if (value == "47-2111.00") return "Electricians";
    if (value == "47-2121.00") return "Glaziers";
    if (value == "47-2131.00") return "Insulation Workers, Floor, Ceiling, and Wall";
    if (value == "47-2132.00") return "Insulation Workers, Mechanical";
    if (value == "47-2141.00") return "Painters, Construction and Maintenance";
    if (value == "47-2142.00") return "Paperhangers";
    if (value == "47-2151.00") return "Pipelayers";
    if (value == "47-2152.00") return "Plumbers, Pipefitters, and Steamfitters";
    if (value == "47-2161.00") return "Plasterers and Stucco Masons";
    if (value == "47-2171.00") return "Reinforcing Iron and Rebar Workers";
    if (value == "47-2181.00") return "Roofers";
    if (value == "47-2211.00") return "Sheet Metal Workers";
    if (value == "47-2221.00") return "Structural Iron and Steel Workers";
    if (value == "47-2231.00") return "Solar Photovoltaic Installers";
    if (value == "47-3011.00") return "Helpers--Brickmasons, Blockmasons, Stonemasons, and Tile and Marble Setters";
    if (value == "47-3012.00") return "Helpers--Carpenters";
    if (value == "47-3013.00") return "Helpers--Electricians";
    if (value == "47-3014.00") return "Helpers--Painters, Paperhangers, Plasterers, and Stucco Masons";
    if (value == "47-3015.00") return "Helpers--Pipelayers, Plumbers, Pipefitters, and Steamfitters";
    if (value == "47-3016.00") return "Helpers--Roofers";
    if (value == "47-3019.00") return "Helpers, Construction Trades, All Other";
    if (value == "47-4011.00") return "Construction and Building Inspectors";
    if (value == "47-4021.00") return "Elevator and Escalator Installers and Repairers";
    if (value == "47-4031.00") return "Fence Erectors";
    if (value == "47-4041.00") return "Hazardous Materials Removal Workers";
    if (value == "47-4051.00") return "Highway Maintenance Workers";
    if (value == "47-4061.00") return "Rail-Track Laying and Maintenance Equipment Operators";
    if (value == "47-4071.00") return "Septic Tank Servicers and Sewer Pipe Cleaners";
    if (value == "47-4091.00") return "Segmental Pavers";
    if (value == "47-4099.00") return "Construction and Related Workers, All Other";
    if (value == "47-5011.00") return "Derrick Operators, Oil and Gas";
    if (value == "47-5012.00") return "Rotary Drill Operators, Oil and Gas";
    if (value == "47-5013.00") return "Service Unit Operators, Oil and Gas";
    if (value == "47-5022.00") return "Excavating and Loading Machine and Dragline Operators, Surface Mining";
    if (value == "47-5023.00") return "Earth Drillers, Except Oil and Gas";
    if (value == "47-5032.00") return "Explosives Workers, Ordnance Handling Experts, and Blasters";
    if (value == "47-5041.00") return "Continuous Mining Machine Operators";
    if (value == "47-5043.00") return "Roof Bolters, Mining";
    if (value == "47-5044.00") return "Loading and Moving Machine Operators, Underground Mining";
    if (value == "47-5049.00") return "Underground Mining Machine Operators, All Other";
    if (value == "47-5051.00") return "Rock Splitters, Quarry";
    if (value == "47-5071.00") return "Roustabouts, Oil and Gas";
    if (value == "47-5081.00") return "Helpers--Extraction Workers";
    if (value == "47-5099.00") return "Extraction Workers, All Other";
    if (value == "49-1011.00") return "First-Line Supervisors of Mechanics, Installers, and Repairers";
    if (value == "49-2011.00") return "Computer, Automated Teller, and Office Machine Repairers";
    if (value == "49-2021.00") return "Radio, Cellular, and Tower Equipment Installers and Repairers";
    if (value == "49-2022.00") return "Telecommunications Equipment Installers and Repairers, Except Line Installers";
    if (value == "49-2091.00") return "Avionics Technicians";
    if (value == "49-2092.00") return "Electric Motor, Power Tool, and Related Repairers";
    if (value == "49-2093.00") return "Electrical and Electronics Installers and Repairers, Transportation Equipment";
    if (value == "49-2094.00") return "Electrical and Electronics Repairers, Commercial and Industrial Equipment";
    if (value == "49-2095.00") return "Electrical and Electronics Repairers, Powerhouse, Substation, and Relay";
    if (value == "49-2096.00") return "Electronic Equipment Installers and Repairers, Motor Vehicles";
    if (value == "49-2097.00") return "Audiovisual Equipment Installers and Repairers";
    if (value == "49-2098.00") return "Security and Fire Alarm Systems Installers";
    if (value == "49-3011.00") return "Aircraft Mechanics and Service Technicians";
    if (value == "49-3021.00") return "Automotive Body and Related Repairers";
    if (value == "49-3022.00") return "Automotive Glass Installers and Repairers";
    if (value == "49-3023.00") return "Automotive Service Technicians and Mechanics";
    if (value == "49-3031.00") return "Bus and Truck Mechanics and Diesel Engine Specialists";
    if (value == "49-3041.00") return "Farm Equipment Mechanics and Service Technicians";
    if (value == "49-3042.00") return "Mobile Heavy Equipment Mechanics, Except Engines";
    if (value == "49-3043.00") return "Rail Car Repairers";
    if (value == "49-3051.00") return "Motorboat Mechanics and Service Technicians";
    if (value == "49-3052.00") return "Motorcycle Mechanics";
    if (value == "49-3053.00") return "Outdoor Power Equipment and Other Small Engine Mechanics";
    if (value == "49-3091.00") return "Bicycle Repairers";
    if (value == "49-3092.00") return "Recreational Vehicle Service Technicians";
    if (value == "49-3093.00") return "Tire Repairers and Changers";
    if (value == "49-9011.00") return "Mechanical Door Repairers";
    if (value == "49-9012.00") return "Control and Valve Installers and Repairers, Except Mechanical Door";
    if (value == "49-9021.00") return "Heating, Air Conditioning, and Refrigeration Mechanics and Installers";
    if (value == "49-9031.00") return "Home Appliance Repairers";
    if (value == "49-9041.00") return "Industrial Machinery Mechanics";
    if (value == "49-9043.00") return "Maintenance Workers, Machinery";
    if (value == "49-9044.00") return "Millwrights";
    if (value == "49-9045.00") return "Refractory Materials Repairers, Except Brickmasons";
    if (value == "49-9051.00") return "Electrical Power-Line Installers and Repairers";
    if (value == "49-9052.00") return "Telecommunications Line Installers and Repairers";
    if (value == "49-9061.00") return "Camera and Photographic Equipment Repairers";
    if (value == "49-9062.00") return "Medical Equipment Repairers";
    if (value == "49-9063.00") return "Musical Instrument Repairers and Tuners";
    if (value == "49-9064.00") return "Watch and Clock Repairers";
    if (value == "49-9069.00") return "Precision Instrument and Equipment Repairers, All Other";
    if (value == "49-9071.00") return "Maintenance and Repair Workers, General";
    if (value == "49-9081.00") return "Wind Turbine Service Technicians";
    if (value == "49-9091.00") return "Coin, Vending, and Amusement Machine Servicers and Repairers";
    if (value == "49-9092.00") return "Commercial Divers";
    if (value == "49-9094.00") return "Locksmiths and Safe Repairers";
    if (value == "49-9095.00") return "Manufactured Building and Mobile Home Installers";
    if (value == "49-9096.00") return "Riggers";
    if (value == "49-9097.00") return "Signal and Track Switch Repairers";
    if (value == "49-9098.00") return "Helpers--Installation, Maintenance, and Repair Workers";
    if (value == "49-9099.00") return "Installation, Maintenance, and Repair Workers, All Other";
    if (value == "51-1011.00") return "First-Line Supervisors of Production and Operating Workers";
    if (value == "51-2011.00") return "Aircraft Structure, Surfaces, Rigging, and Systems Assemblers";
    if (value == "51-2021.00") return "Coil Winders, Tapers, and Finishers";
    if (value == "51-2022.00") return "Electrical and Electronic Equipment Assemblers";
    if (value == "51-2023.00") return "Electromechanical Equipment Assemblers";
    if (value == "51-2031.00") return "Engine and Other Machine Assemblers";
    if (value == "51-2041.00") return "Structural Metal Fabricators and Fitters";
    if (value == "51-2051.00") return "Fiberglass Laminators and Fabricators";
    if (value == "51-2061.00") return "Timing Device Assemblers and Adjusters";
    if (value == "51-2092.00") return "Team Assemblers";
    if (value == "51-2099.00") return "Assemblers and Fabricators, All Other";
    if (value == "51-3011.00") return "Bakers";
    if (value == "51-3021.00") return "Butchers and Meat Cutters";
    if (value == "51-3022.00") return "Meat, Poultry, and Fish Cutters and Trimmers";
    if (value == "51-3023.00") return "Slaughterers and Meat Packers";
    if (value == "51-3091.00") return "Food and Tobacco Roasting, Baking, and Drying Machine Operators and Tenders";
    if (value == "51-3092.00") return "Food Batchmakers";
    if (value == "51-3093.00") return "Food Cooking Machine Operators and Tenders";
    if (value == "51-3099.00") return "Food Processing Workers, All Other";
    if (value == "51-4021.00") return "Extruding and Drawing Machine Setters, Operators, and Tenders, Metal and Plastic";
    if (value == "51-4022.00") return "Forging Machine Setters, Operators, and Tenders, Metal and Plastic";
    if (value == "51-4023.00") return "Rolling Machine Setters, Operators, and Tenders, Metal and Plastic";
    if (value == "51-4031.00") return "Cutting, Punching, and Press Machine Setters, Operators, and Tenders, Metal and Plastic";
    if (value == "51-4032.00") return "Drilling and Boring Machine Tool Setters, Operators, and Tenders, Metal and Plastic";
    if (value == "51-4033.00") return "Grinding, Lapping, Polishing, and Buffing Machine Tool Setters, Operators, and Tenders, Metal and Plastic";
    if (value == "51-4034.00") return "Lathe and Turning Machine Tool Setters, Operators, and Tenders, Metal and Plastic";
    if (value == "51-4035.00") return "Milling and Planing Machine Setters, Operators, and Tenders, Metal and Plastic";
    if (value == "51-4041.00") return "Machinists";
    if (value == "51-4051.00") return "Metal-Refining Furnace Operators and Tenders";
    if (value == "51-4052.00") return "Pourers and Casters, Metal";
    if (value == "51-4061.00") return "Model Makers, Metal and Plastic";
    if (value == "51-4062.00") return "Patternmakers, Metal and Plastic";
    if (value == "51-4071.00") return "Foundry Mold and Coremakers";
    if (value == "51-4072.00") return "Molding, Coremaking, and Casting Machine Setters, Operators, and Tenders, Metal and Plastic";
    if (value == "51-4081.00") return "Multiple Machine Tool Setters, Operators, and Tenders, Metal and Plastic";
    if (value == "51-4111.00") return "Tool and Die Makers";
    if (value == "51-4121.00") return "Welders, Cutters, Solderers, and Brazers";
    if (value == "51-4122.00") return "Welding, Soldering, and Brazing Machine Setters, Operators, and Tenders";
    if (value == "51-4191.00") return "Heat Treating Equipment Setters, Operators, and Tenders, Metal and Plastic";
    if (value == "51-4192.00") return "Layout Workers, Metal and Plastic";
    if (value == "51-4193.00") return "Plating Machine Setters, Operators, and Tenders, Metal and Plastic";
    if (value == "51-4194.00") return "Tool Grinders, Filers, and Sharpeners";
    if (value == "51-4199.00") return "Metal Workers and Plastic Workers, All Other";
    if (value == "51-5111.00") return "Prepress Technicians and Workers";
    if (value == "51-5112.00") return "Printing Press Operators";
    if (value == "51-5113.00") return "Print Binding and Finishing Workers";
    if (value == "51-6011.00") return "Laundry and Dry-Cleaning Workers";
    if (value == "51-6021.00") return "Pressers, Textile, Garment, and Related Materials";
    if (value == "51-6031.00") return "Sewing Machine Operators";
    if (value == "51-6041.00") return "Shoe and Leather Workers and Repairers";
    if (value == "51-6042.00") return "Shoe Machine Operators and Tenders";
    if (value == "51-6051.00") return "Sewers, Hand";
    if (value == "51-6052.00") return "Tailors, Dressmakers, and Custom Sewers";
    if (value == "51-6061.00") return "Textile Bleaching and Dyeing Machine Operators and Tenders";
    if (value == "51-6062.00") return "Textile Cutting Machine Setters, Operators, and Tenders";
    if (value == "51-6063.00") return "Textile Knitting and Weaving Machine Setters, Operators, and Tenders";
    if (value == "51-6064.00") return "Textile Winding, Twisting, and Drawing Out Machine Setters, Operators, and Tenders";
    if (value == "51-6091.00") return "Extruding and Forming Machine Setters, Operators, and Tenders, Synthetic and Glass Fibers";
    if (value == "51-6092.00") return "Fabric and Apparel Patternmakers";
    if (value == "51-6093.00") return "Upholsterers";
    if (value == "51-6099.00") return "Textile, Apparel, and Furnishings Workers, All Other";
    if (value == "51-7011.00") return "Cabinetmakers and Bench Carpenters";
    if (value == "51-7021.00") return "Furniture Finishers";
    if (value == "51-7031.00") return "Model Makers, Wood";
    if (value == "51-7032.00") return "Patternmakers, Wood";
    if (value == "51-7041.00") return "Sawing Machine Setters, Operators, and Tenders, Wood";
    if (value == "51-7042.00") return "Woodworking Machine Setters, Operators, and Tenders, Except Sawing";
    if (value == "51-7099.00") return "Woodworkers, All Other";
    if (value == "51-8011.00") return "Nuclear Power Reactor Operators";
    if (value == "51-8012.00") return "Power Distributors and Dispatchers";
    if (value == "51-8013.00") return "Power Plant Operators";
    if (value == "51-8021.00") return "Stationary Engineers and Boiler Operators";
    if (value == "51-8031.00") return "Water and Wastewater Treatment Plant and System Operators";
    if (value == "51-8091.00") return "Chemical Plant and System Operators";
    if (value == "51-8092.00") return "Gas Plant Operators";
    if (value == "51-8093.00") return "Petroleum Pump System Operators, Refinery Operators, and Gaugers";
    if (value == "51-8099.00") return "Plant and System Operators, All Other";
    if (value == "51-9011.00") return "Chemical Equipment Operators and Tenders";
    if (value == "51-9012.00") return "Separating, Filtering, Clarifying, Precipitating, and Still Machine Setters, Operators, and Tenders";
    if (value == "51-9021.00") return "Crushing, Grinding, and Polishing Machine Setters, Operators, and Tenders";
    if (value == "51-9022.00") return "Grinding and Polishing Workers, Hand";
    if (value == "51-9023.00") return "Mixing and Blending Machine Setters, Operators, and Tenders";
    if (value == "51-9031.00") return "Cutters and Trimmers, Hand";
    if (value == "51-9032.00") return "Cutting and Slicing Machine Setters, Operators, and Tenders";
    if (value == "51-9041.00") return "Extruding, Forming, Pressing, and Compacting Machine Setters, Operators, and Tenders";
    if (value == "51-9051.00") return "Furnace, Kiln, Oven, Drier, and Kettle Operators and Tenders";
    if (value == "51-9061.00") return "Inspectors, Testers, Sorters, Samplers, and Weighers";
    if (value == "51-9071.00") return "Jewelers and Precious Stone and Metal Workers";
    if (value == "51-9081.00") return "Dental Laboratory Technicians";
    if (value == "51-9082.00") return "Medical Appliance Technicians";
    if (value == "51-9083.00") return "Ophthalmic Laboratory Technicians";
    if (value == "51-9111.00") return "Packaging and Filling Machine Operators and Tenders";
    if (value == "51-9123.00") return "Painting, Coating, and Decorating Workers";
    if (value == "51-9124.00") return "Coating, Painting, and Spraying Machine Setters, Operators, and Tenders";
    if (value == "51-9141.00") return "Semiconductor Processing Technicians";
    if (value == "51-9151.00") return "Photographic Process Workers and Processing Machine Operators";
    if (value == "51-9161.00") return "Computer Numerically Controlled Tool Operators";
    if (value == "51-9162.00") return "Computer Numerically Controlled Tool Programmers";
    if (value == "51-9191.00") return "Adhesive Bonding Machine Operators and Tenders";
    if (value == "51-9192.00") return "Cleaning, Washing, and Metal Pickling Equipment Operators and Tenders";
    if (value == "51-9193.00") return "Cooling and Freezing Equipment Operators and Tenders";
    if (value == "51-9194.00") return "Etchers and Engravers";
    if (value == "51-9195.00") return "Molders, Shapers, and Casters, Except Metal and Plastic";
    if (value == "51-9196.00") return "Paper Goods Machine Setters, Operators, and Tenders";
    if (value == "51-9197.00") return "Tire Builders";
    if (value == "51-9198.00") return "Helpers--Production Workers";
    if (value == "51-9199.00") return "Production Workers, All Other";
    if (value == "53-1041.00") return "Aircraft Cargo Handling Supervisors";
    if (value == "53-1042.00") return "First-Line Supervisors of Helpers, Laborers, and Material Movers, Hand";
    if (value == "53-1043.00") return "First-Line Supervisors of Material-Moving Machine and Vehicle Operators";
    if (value == "53-1044.00") return "First-line Supervisors of Passenger Attendants";
    if (value == "53-1049.00") return "First Line Supervisors of Transportation Workers, All Other";
    if (value == "53-2011.00") return "Airline Pilots, Copilots, and Flight Engineers";
    if (value == "53-2012.00") return "Commercial Pilots";
    if (value == "53-2021.00") return "Air Traffic Controllers";
    if (value == "53-2022.00") return "Airfield Operations Specialists";
    if (value == "53-2031.00") return "Flight Attendants";
    if (value == "53-3011.00") return "Ambulance Drivers and Attendants, Except Emergency Medical Technicians";
    if (value == "53-3031.00") return "Driver/Sales Workers";
    if (value == "53-3032.00") return "Heavy and Tractor-Trailer Truck Drivers";
    if (value == "53-3033.00") return "Light Truck Drivers";
    if (value == "53-3051.00") return "Bus Drivers, School";
    if (value == "53-3052.00") return "Bus Drivers, Transit and Intercity";
    if (value == "53-3053.00") return "Shuttle Drivers and Chauffeurs";
    if (value == "53-3054.00") return "Taxi Drivers";
    if (value == "53-3099.00") return "Motor Vehicle Operators, All Other";
    if (value == "53-4011.00") return "Locomotive Engineers";
    if (value == "53-4013.00") return "Rail Yard Engineers, Dinkey Operators, and Hostlers";
    if (value == "53-4022.00") return "Railroad Brake, Signal, and Switch Operators and Locomotive Firers";
    if (value == "53-4031.00") return "Railroad Conductors and Yardmasters";
    if (value == "53-4041.00") return "Subway and Streetcar Operators";
    if (value == "53-4099.00") return "Rail Transportation Workers, All Other";
    if (value == "53-5011.00") return "Sailors and Marine Oilers";
    if (value == "53-5021.00") return "Captains, Mates, and Pilots of Water Vessels";
    if (value == "53-5022.00") return "Motorboat Operators";
    if (value == "53-5031.00") return "Ship Engineers";
    if (value == "53-6011.00") return "Bridge and Lock Tenders";
    if (value == "53-6021.00") return "Parking Attendants";
    if (value == "53-6031.00") return "Automotive and Watercraft Service Attendants";
    if (value == "53-6032.00") return "Aircraft Service Attendants";
    if (value == "53-6041.00") return "Traffic Technicians";
    if (value == "53-6051.00") return "Transportation Inspectors";
    if (value == "53-6061.00") return "Passenger Attendants";
    if (value == "53-6099.00") return "Transportation Workers, All Other";
    if (value == "53-7011.00") return "Conveyor Operators and Tenders";
    if (value == "53-7021.00") return "Crane and Tower Operators";
    if (value == "53-7031.00") return "Dredge Operators";
    if (value == "53-7041.00") return "Hoist and Winch Operators";
    if (value == "53-7051.00") return "Industrial Truck and Tractor Operators";
    if (value == "53-7061.00") return "Cleaners of Vehicles and Equipment";
    if (value == "53-7062.00") return "Laborers and Freight, Stock, and Material Movers, Hand";
    if (value == "53-7063.00") return "Machine Feeders and Offbearers";
    if (value == "53-7064.00") return "Packers and Packagers, Hand";
    if (value == "53-7065.00") return "Stockers and Order Fillers";
    if (value == "53-7071.00") return "Gas Compressor and Gas Pumping Station Operators";
    if (value == "53-7072.00") return "Pump Operators, Except Wellhead Pumpers";
    if (value == "53-7073.00") return "Wellhead Pumpers";
    if (value == "53-7081.00") return "Refuse and Recyclable Material Collectors";
    if (value == "53-7121.00") return "Tank Car, Truck, and Ship Loaders";
    if (value == "53-7199.00") return "Material Moving Workers, All Other";
    if (value == "55-1011.00") return "Air Crew Officers";
    if (value == "55-1012.00") return "Aircraft Launch and Recovery Officers";
    if (value == "55-1013.00") return "Armored Assault Vehicle Officers";
    if (value == "55-1014.00") return "Artillery and Missile Officers";
    if (value == "55-1015.00") return "Command and Control Center Officers";
    if (value == "55-1016.00") return "Infantry Officers";
    if (value == "55-1017.00") return "Special Forces Officers";
    if (value == "55-1019.00") return "Military Officer Special and Tactical Operations Leaders, All Other";
    if (value == "55-2011.00") return "First-Line Supervisors of Air Crew Members";
    if (value == "55-2012.00") return "First-Line Supervisors of Weapons Specialists/Crew Members";
    if (value == "55-2013.00") return "First-Line Supervisors of All Other Tactical Operations Specialists";
    if (value == "55-3011.00") return "Air Crew Members";
    if (value == "55-3012.00") return "Aircraft Launch and Recovery Specialists";
    if (value == "55-3013.00") return "Armored Assault Vehicle Crew Members";
    if (value == "55-3014.00") return "Artillery and Missile Crew Members";
    if (value == "55-3015.00") return "Command and Control Center Specialists";
    if (value == "55-3016.00") return "Infantry";
    if (value == "55-3018.00") return "Special Forces";
    if (value == "55-3019.00") return "Military Enlisted Tactical Operations and Air/Weapons Specialists and Crew Members, All Other";
    if (value == "17-2112.01") return "Human Factors Engineers and Ergonomists";
    if (value == "11-9199.09") return "Wind Energy Operations Managers ";
    if (value == "15-1199.07") return "Data Warehousing Specialists";
    if (value == "13-1199.02") return "Security Management Specialists ";
    if (value == "15-2041.01") return "Biostatisticians";
    if (value == "11-9199.07") return "Security Managers";
    if (value == "11-9199.02") return "Compliance Managers ";
    if (value == "17-2199.07") return "Photonics Engineers";
    if (value == "11-9199.11") return "Brownfield Redevelopment Specialists and Site Managers ";
    if (value == "19-1029.01") return "Bioinformatics Scientists";
    if (value == "11-3071.03") return "Logistics Managers";
    if (value == "15-1199.06") return "Database Architects ";
    if (value == "13-1199.06") return "Online Merchants ";
    if (value == "17-2199.05") return "Mechatronics Engineers";
    if (value == "15-1199.01") return "Software Quality Assurance Engineers and Testers ";
    if (value == "15-1199.05") return "Geographic Information Systems Technicians ";
    if (value == "15-1199.03") return "Web Administrators ";
    if (value == "15-1199.08") return "Business Intelligence Analysts ";
    if (value == "13-2099.02") return "Risk Management Specialists";

    else return "";
}